#ifndef PARSER_DEF
#define PARSER_DEF
#endif

#include "lexerDef.h"

typedef enum {
  NT_PROGRAM,
  NT_MAINFUNCTION,
  NT_OTHERFUNCTIONS,
  NT_FUNCTION,
  NT_INPUT_PAR,
  NT_OUTPUT_PAR,
  NT_PARAMETER_LIST,
  NT_DATATYPE,
  NT_PRIMITIVEDATATYPE,
  NT_CONSTRUCTEDDATATYPE,
  NT_REMAINING_LIST,
  NT_STMTS,
  NT_TYPEDEFINITIONS,
  NT_ACTUALORREDEFINED,
  NT_TYPEDEFINITION,
  NT_FIELDDEFINITIONS,
  NT_FIELDDEFINITION,
  NT_FIELDTYPE,
  NT_MOREFIELDS,
  NT_DECLATRATIONS,
  NT_DECLATRATION,
  NT_GLOBAL_OR_NOT,
  NT_OTHERSTMTS,
  NT_STMT,
  NT_ASSIGNMENTSTMT,
  NT_SINGLEORRECID,
  NT_OPTION_SINGLE_CONSTRUCTED,
  NT_ONEEXPANSION,
  NT_MOREEXPANSIONS,
  NT_FUNCALLSTMT,
  NT_OUTPUTPARAMETERS,
  NT_INPUTPARAMETERS,
  NT_ITERATIVESTMT,
  NT_CONDITIONALSTMT,
  NT_ELSEPART,
  NT_IOSTMT,
  NT_ARITHMETICEXPRESSION,
  NT_EXPPRIME,
  NT_TERM,
  NT_TERMPRIME,
  NT_FACTOR,
  NT_HIGHPRECEDENCEOPERATORS,
  NT_LOWPRECEDENCEOPERATORS,
  NT_BOOLEANEXPRESSION,
  NT_VAR,
  NT_LOGICALOP,
  NT_RELATIONALOP,
  NT_RETURNSTMT,
  NT_OPTIONALRETURN,
  NT_IDLIST,
  NT_MORE_IDS,
  NT_DEFINETYPESTMT,
  NT_A,
  EPSILLON,
  NULL_NT, // only to be used for grammar_rule_element
} NON_TERMINAL;

typedef struct {
  bool terminal;
  union {
    TOKEN_TYPE t;
    NON_TERMINAL nt;
  } var;
} grammar_element;

typedef struct {
  grammar_element elements[10];
  int element_count;
} grammar_rule;

typedef struct {
  grammar_rule rules[53][10];
  int rule_count[53];
  bool has_epsillon[53];
} grammar;
